<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260930173357 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial : utilisateurs, applications (clients OAuth2), accès et jetons';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE oauth2_access_token (
              identifier CHAR(80) NOT NULL,
              expiry TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_identifier VARCHAR(128) DEFAULT NULL,
              scopes TEXT DEFAULT NULL,
              revoked BOOLEAN NOT NULL,
              client VARCHAR(32) NOT NULL,
              PRIMARY KEY (identifier)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_454D9673C7440455 ON oauth2_access_token (client)');
        $this->addSql(<<<'SQL'
            CREATE TABLE oauth2_authorization_code (
              identifier CHAR(80) NOT NULL,
              expiry TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_identifier VARCHAR(128) DEFAULT NULL,
              scopes TEXT DEFAULT NULL,
              revoked BOOLEAN NOT NULL,
              client VARCHAR(32) NOT NULL,
              PRIMARY KEY (identifier)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_509FEF5FC7440455 ON oauth2_authorization_code (client)');
        $this->addSql(<<<'SQL'
            CREATE TABLE oauth2_client (
              name VARCHAR(128) NOT NULL,
              secret VARCHAR(128) DEFAULT NULL,
              redirect_uris TEXT DEFAULT NULL,
              grants TEXT DEFAULT NULL,
              scopes TEXT DEFAULT NULL,
              active BOOLEAN NOT NULL,
              allow_plain_text_pkce BOOLEAN DEFAULT false NOT NULL,
              identifier VARCHAR(32) NOT NULL,
              description TEXT DEFAULT NULL,
              home_url VARCHAR(255) DEFAULT NULL,
              open_registration BOOLEAN DEFAULT false NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (identifier)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE oauth2_refresh_token (
              identifier CHAR(80) NOT NULL,
              expiry TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              revoked BOOLEAN NOT NULL,
              access_token CHAR(80) DEFAULT NULL,
              PRIMARY KEY (identifier)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_4DD90732B6A2DD68 ON oauth2_refresh_token (access_token)');
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              display_name VARCHAR(100) NOT NULL,
              roles JSON NOT NULL,
              password VARCHAR(255) NOT NULL,
              enabled BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql(<<<'SQL'
            CREATE TABLE user_application (
              user_id INT NOT NULL,
              application_id VARCHAR(32) NOT NULL,
              PRIMARY KEY (user_id, application_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_D401454A76ED395 ON user_application (user_id)');
        $this->addSql('CREATE INDEX IDX_D4014543E030ACD ON user_application (application_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              oauth2_access_token
            ADD
              CONSTRAINT FK_454D9673C7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              oauth2_authorization_code
            ADD
              CONSTRAINT FK_509FEF5FC7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              oauth2_refresh_token
            ADD
              CONSTRAINT FK_4DD90732B6A2DD68 FOREIGN KEY (access_token) REFERENCES oauth2_access_token (identifier) ON DELETE
            SET
              NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_application
            ADD
              CONSTRAINT FK_D401454A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_application
            ADD
              CONSTRAINT FK_D4014543E030ACD FOREIGN KEY (application_id) REFERENCES oauth2_client (identifier) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE oauth2_access_token DROP CONSTRAINT FK_454D9673C7440455');
        $this->addSql('ALTER TABLE oauth2_authorization_code DROP CONSTRAINT FK_509FEF5FC7440455');
        $this->addSql('ALTER TABLE oauth2_refresh_token DROP CONSTRAINT FK_4DD90732B6A2DD68');
        $this->addSql('ALTER TABLE user_application DROP CONSTRAINT FK_D401454A76ED395');
        $this->addSql('ALTER TABLE user_application DROP CONSTRAINT FK_D4014543E030ACD');
        $this->addSql('DROP TABLE oauth2_access_token');
        $this->addSql('DROP TABLE oauth2_authorization_code');
        $this->addSql('DROP TABLE oauth2_client');
        $this->addSql('DROP TABLE oauth2_refresh_token');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_application');
    }
}
